apiVersion: v1
data:
  overrides.yaml: |
    overrides: {}
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"overrides.yaml":"overrides: {}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"overrides","namespace":"loki"}}
  creationTimestamp: "2021-02-22T11:21:30Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:overrides.yaml: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-02-22T11:21:30Z"
  name: overrides
  namespace: loki
  resourceVersion: "75161"
  selfLink: /api/v1/namespaces/loki/configmaps/overrides
  uid: 62dcd6e4-0c0c-4c20-ba4c-6f6b9b2396d4
