apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"policy/v1beta1","kind":"PodDisruptionBudget","metadata":{"annotations":{},"labels":{"name":"loki-ingester-pdb"},"name":"loki-ingester-pdb","namespace":"loki"},"spec":{"maxUnavailable":1,"selector":{"matchLabels":{"name":"ingester"}}}}
  creationTimestamp: "2021-02-22T11:21:26Z"
  generation: 1
  labels:
    name: loki-ingester-pdb
  managedFields:
  - apiVersion: policy/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:name: {}
      f:spec:
        f:maxUnavailable: {}
        f:selector:
          .: {}
          f:matchLabels:
            .: {}
            f:name: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-02-22T11:21:26Z"
  - apiVersion: policy/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:desiredHealthy: {}
        f:expectedPods: {}
        f:observedGeneration: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-02-22T11:30:59Z"
  name: loki-ingester-pdb
  namespace: loki
  resourceVersion: "79011"
  selfLink: /apis/policy/v1beta1/namespaces/loki/poddisruptionbudgets/loki-ingester-pdb
  uid: 840ffdbb-d7df-4d6a-ae86-b386c09508d0
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      name: ingester
status:
  currentHealthy: 0
  desiredHealthy: 1
  disruptionsAllowed: 0
  expectedPods: 2
  observedGeneration: 1
