apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"name":"memcached","namespace":"loki"},"spec":{"replicas":3,"selector":{"matchLabels":{"name":"memcached"}},"serviceName":"memcached","template":{"metadata":{"labels":{"name":"memcached"}},"spec":{"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchLabels":{"name":"memcached"}},"topologyKey":"kubernetes.io/hostname"}]}},"containers":[{"args":["-m 4096","-I 2m","-c 1024","-v"],"image":"memcached:1.5.17-alpine","imagePullPolicy":"IfNotPresent","name":"memcached","ports":[{"containerPort":11211,"name":"client"}],"resources":{"limits":{"cpu":"3","memory":"6Gi"},"requests":{"cpu":"500m","memory":"5016Mi"}}},{"args":["--memcached.address=localhost:11211","--web.listen-address=0.0.0.0:9150"],"image":"prom/memcached-exporter:v0.6.0","imagePullPolicy":"IfNotPresent","name":"exporter","ports":[{"containerPort":9150,"name":"http-metrics"}]}]}},"updateStrategy":{"type":"RollingUpdate"}}}
  creationTimestamp: "2021-02-22T11:21:46Z"
  generation: 1
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:collisionCount: {}
        f:currentReplicas: {}
        f:currentRevision: {}
        f:observedGeneration: {}
        f:replicas: {}
        f:updateRevision: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-02-22T11:21:46Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:podManagementPolicy: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:name: {}
        f:serviceName: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:name: {}
          f:spec:
            f:affinity:
              .: {}
              f:podAntiAffinity:
                .: {}
                f:requiredDuringSchedulingIgnoredDuringExecution: {}
            f:containers:
              k:{"name":"exporter"}:
                .: {}
                f:args: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":9150,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
              k:{"name":"memcached"}:
                .: {}
                f:args: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":11211,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:resources:
                  .: {}
                  f:limits:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                  f:requests:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
        f:updateStrategy:
          f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-02-22T11:21:46Z"
  name: memcached
  namespace: loki
  resourceVersion: "75436"
  selfLink: /apis/apps/v1/namespaces/loki/statefulsets/memcached
  uid: 68906780-9cbd-4903-b6d4-17f14c3728d5
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: memcached
  serviceName: memcached
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: memcached
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                name: memcached
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - -m 4096
        - -I 2m
        - -c 1024
        - -v
        image: memcached:1.5.17-alpine
        imagePullPolicy: IfNotPresent
        name: memcached
        ports:
        - containerPort: 11211
          name: client
          protocol: TCP
        resources:
          limits:
            cpu: "3"
            memory: 6Gi
          requests:
            cpu: 500m
            memory: 5016Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --memcached.address=localhost:11211
        - --web.listen-address=0.0.0.0:9150
        image: prom/memcached-exporter:v0.6.0
        imagePullPolicy: IfNotPresent
        name: exporter
        ports:
        - containerPort: 9150
          name: http-metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: memcached-876bbddff
  observedGeneration: 1
  replicas: 1
  updateRevision: memcached-876bbddff
  updatedReplicas: 1
