apiVersion: v1
data:
  promtail.yml: |
    clients:
      - url: http://loki:password@gateway.loki.svc/loki/api/v1/push
    scrape_configs:
    - job_name: journal
      journal:
        labels:
          job: systemd-journal
        max_age: 12h
        path: /var/log/journal
      pipeline_stages:
        - replace:
            # IP4
            expression: '(\d{1,3}[.]\d{1,3}[.]\d{1,3}[.]\d{1,3})'
            replace: '*IP4*{{ .Value | Hash "salt" }}*'
        - replace:
            # pod_name
            #expression: '[a-z]+\-+[a-z0-9]+\-+[a-z0-9]+'
            #expression: '([[^zalenium]+[-]+[a-z0-9]+[-]+[a-z0-9]+])'
            expression: '(zalenium+[-]+[a-z0-9]+[-]+[a-z0-9]+)'
            replace: '************'
        - replace:
            # IP4
            expression: '((?:\w[.]*?){32}])'
            replace: 'extid*********************extid'
      relabel_configs:
      - source_labels:
        - __journal__systemd_unit
        target_label: system_unit
      - source_labels:
        - __journal_priority
        target_label: system_priority
      - source_labels:
        - __journal__hostname
        target_label: system_hostname
      - source_labels:
        - __journal__transport
        target_label: system_transport
      - action: drop
        regex: .+
        source_labels:
        - __journal__audit_id
      - source_labels: ['__journal_container_name']
        regex: ^([^_]+)_([^\._]+)(\.([^_]+))?_([^_]+)_([^_]+)_[^_]+_[^_]+$
        target_label: 'namespace'
        replacement: '${6}'

      - source_labels: ['__journal_container_name']
        regex: ^([^_]+)_([^\._]+)(\.([^_]+))?_([^_]+)_([^_]+)_[^_]+_[^_]+$
        target_label: 'instance'
        replacement: '${5}'

      - source_labels: ['__journal_container_name']
        regex: ^([^_]+)_([^\._]+)(\.([^_]+))?_([^_]+)_([^_]+)_[^_]+_[^_]+$
        target_label: 'container_name'
        replacement: '${2}'

kind: ConfigMap
metadata:
  name: promtail
  namespace: loki
